id: 478789354d9041a2bccb55c295e9f879
title: Toh_184-Teaching_the_Practice_of_a_Bodhisattva-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-004
  eft-text-version: 1.0.10 2020
